# Generated by Django 5.0.6 on 2024-07-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rem",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="nos",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bus",
            name="nos",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="bus",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bus",
            name="rem",
            field=models.PositiveIntegerField(),
        ),
    ]
