# Generated by Django 5.0.6 on 2024-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_book_rem_alter_book_nos_alter_book_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="rem",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
