# Generated by Django 5.0.6 on 2024-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_bus_rem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rem",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
